## Part 2.1: Introduction to Pandas and NumPy for Data Analysis

## Introduction to NumPy

Importing the NumPy library and creating a NumPy ndarray:

In [1]:
## import numpy library and refer to it as np
import numpy as np
## create a numpy 1D array (ndarray = n-dimensional array)
data_ndarray = np.array([10, 20, 30])
print(data_ndarray)
print(type(data_ndarray))

[10 20 30]
<class 'numpy.ndarray'>


Importing the nyc_taxis csv and converting to a NumPy array:

In [4]:
from csv import reader

# import nyc_taxi.csv as a list of lists
opened_file = open("nyc_taxis.csv", "r", encoding='UTF8')
taxi_list = list(reader(opened_file))

# remove the header row
taxi_list = taxi_list[1:]

# convert all values to floats
converted_taxi_list = []

# for each row/list in the list of lists
for row in taxi_list:
    converted_row = []
    
    # for each item in the row/list
    for item in row:
        
        # convert each item into a float item within a new list
        converted_row.append(float(item))
    
    # append each row to a converted list of the whole taxi_list
    converted_taxi_list.append(converted_row)

# convert this list of lists into a numpy ndarray
taxi = np.array(converted_taxi_list)

Querying the shape of arrays:

In [5]:
print(taxi)

data_ndarray = np.array([[5, 10, 15],[20, 25, 30]])
print(data_ndarray.shape)

taxi_shape = taxi.shape
print(taxi_shape)

[[2.016e+03 1.000e+00 1.000e+00 ... 1.165e+01 6.999e+01 1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 8.000e+00 5.430e+01 1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 0.000e+00 3.780e+01 2.000e+00]
 ...
 [2.016e+03 6.000e+00 3.000e+01 ... 5.000e+00 6.334e+01 1.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 8.950e+00 4.475e+01 1.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 0.000e+00 5.484e+01 2.000e+00]]
(2, 3)
(2013, 15)


In [9]:
np.set_printoptions(suppress=True)
print(taxi)
np.set_printoptions(suppress=False)

data_ndarray = np.array([[5, 10, 15],[20, 25, 30]])
print(data_ndarray.shape)

taxi_shape = taxi.shape
print(taxi_shape)

[[2016.      1.      1.   ...   11.65   69.99    1.  ]
 [2016.      1.      1.   ...    8.     54.3     1.  ]
 [2016.      1.      1.   ...    0.     37.8     2.  ]
 ...
 [2016.      6.     30.   ...    5.     63.34    1.  ]
 [2016.      6.     30.   ...    8.95   44.75    1.  ]
 [2016.      6.     30.   ...    0.     54.84    2.  ]]
(2, 3)
(2013, 15)


There are 2 rows and 3 columns in the first array.

There are 2013 rows and 15 columns in the taxi array.

Selecting rows/items using NumPy ndarrays:

In [ ]:
## the first row
row_0 = taxi[0]

## a range of rows
rows_391_to_500 = taxi[391:501]

## a specific row and column
row_21_column_5 = taxi[21,5]

Selecting seprated columns/rows/items using NumPy ndarrays.

In [ ]:
# determining a set of columns
cols = [1,4,7]

# selecting columns from array using a globally determined set of columns
columns_1_4_7 = taxi[:,cols]
## equivalent to 
## columns_1_4_7 = taxi[:1,4,7]

row_99_columns_5_to_8 = taxi[99,5:9]

rows_100_to_200_column_14 = taxi[100:201,14]

Vectorized operations:
Slicing columns and performing functions:

In [11]:
fare_amount = taxi[:,9]
fees_amount = taxi[:,10]

fare_and_fees = fare_amount + fees_amount
print(fare_and_fees)

[52.8 46.3 37.8 ... 52.8 35.8 49.3]


In [12]:
trip_distance_miles = taxi[:,7]
trip_length_seconds = taxi[:,8]

trip_length_hours = trip_length_seconds / 3600 # 3600 seconds is one hour

trip_mph = trip_distance_miles / trip_length_hours
print(trip_mph)

[37.11340206 38.58157895 31.27222982 ... 22.29907867 42.41551247
 36.90473407]


Calculating statistics for 1D Ndarrays:

In [14]:
mph_min = trip_mph.min()
mph_max = trip_mph.max()
mph_mean = trip_mph.mean()
print(mph_min)
print(mph_max)
print(mph_mean)

0.0
82800.0
169.98315083655157


Calculating statistics for 2D Ndarrays:

In [15]:
# we'll compare against the first 5 rows only
taxi_first_five = taxi[:5]

# select these columns: fare_amount, fees_amount, tolls_amount, tip_amount
fare_components = taxi_first_five[:,9:13]

fare_sums = fare_components.sum(axis=1)

fare_totals = taxi_first_five[:,13]

print(fare_totals)
print(fare_sums)

[69.99 54.3  37.8  32.76 18.8 ]
[69.99 54.3  37.8  32.76 18.8 ]


## Boolean Indexing with NumPy

Generating NumPy Ndarrays direct from csv files:

In [30]:
import numpy as np
np.set_printoptions(suppress=True) 
## Added this separately as list items were appearing with scientific notation

taxi = np.genfromtxt("nyc_taxis.csv", delimiter=",", encoding=None)
taxi_shape = taxi.shape

print(taxi[:3])
print(taxi.dtype)
print(taxi_shape)

np.set_printoptions(suppress=False)

[[    nan     nan     nan     nan     nan     nan     nan     nan     nan
      nan     nan     nan     nan     nan     nan]
 [2016.      1.      1.      5.      0.      2.      4.     21.   2037.
    52.      0.8     5.54   11.65   69.99    1.  ]
 [2016.      1.      1.      5.      0.      2.      1.     16.29 1520.
    45.      1.3     0.      8.     54.3     1.  ]]
float64
(2014, 15)


The header row reults with NaN (not a number) due to np choosing float64 as the data type.

We can use dtype=None and result with <U21 datatype (unicode - 21 characters) or,
we can remove the header first and stick with a float64 datatype array.

In [31]:
import numpy as np
np.set_printoptions(suppress=True)

taxi = np.genfromtxt("nyc_taxis.csv", delimiter=",", dtype=None, encoding=None)
taxi_shape = taxi.shape

print(taxi[:3])
print(taxi.dtype)
print(taxi_shape)

np.set_printoptions(suppress=False)

[['pickup_year' 'pickup_month' 'pickup_day' 'pickup_dayofweek'
  'pickup_time' 'pickup_location_code' 'dropoff_location_code'
  'trip_distance' 'trip_length' 'fare_amount' 'fees_amount'
  'tolls_amount' 'tip_amount' 'total_amount' 'payment_type']
 ['2016' '1' '1' '5' '0' '2' '4' '21.00' '2037' '52.00' '0.80' '5.54'
  '11.65' '69.99' '1']
 ['2016' '1' '1' '5' '0' '2' '1' '16.29' '1520' '45.00' '1.30' '0.00'
  '8.00' '54.30' '1']]
<U21
(2014, 15)


In [33]:
import numpy as np
np.set_printoptions(suppress=True)

taxi = np.genfromtxt("nyc_taxis.csv", delimiter=",", skip_header=1, encoding=None)
taxi_shape = taxi.shape

print(taxi[:3])
print(taxi.dtype)
print(taxi_shape)

np.set_printoptions(suppress=False)

[[2016.      1.      1.      5.      0.      2.      4.     21.   2037.
    52.      0.8     5.54   11.65   69.99    1.  ]
 [2016.      1.      1.      5.      0.      2.      1.     16.29 1520.
    45.      1.3     0.      8.     54.3     1.  ]
 [2016.      1.      1.      5.      0.      2.      6.     12.7  1462.
    36.5     1.3     0.      0.     37.8     2.  ]]
float64
(2013, 15)


Boolean arrays:

In [34]:
a = np.array([1, 2, 3, 4, 5])
b = np.array(["blue", "blue", "red", "blue"])
c = np.array([80.0, 103.4, 96.9, 200.3])

a_bool = a < 3
print(a_bool)
b_bool = b == "blue"
print(b_bool)
c_bool = c > 100
print(c_bool)

[ True  True False False False]
[ True  True False  True]
[False  True False  True]


Using boolean arrays to determine number of rides:

In [35]:
## Create an 1D ndarray that is the first column from the taxis ndarray
pickup_month = taxi[:,1]
print(pickup_month[:4])
print(len(pickup_month))
      
## Create a boolean array of whether the first column in pickup_month is 1
january_bool = pickup_month == 1
print(january_bool[:4])
print(len(january_bool))
      
## Create a new array of pickup_month, filtered using the january_bool index, called january_bool
january = pickup_month[january_bool]
print(january[:4])

## Check the length of the new array, after filtering
january_rides = january.shape[0]
print(january_rides)

## for February
february_bool = pickup_month == 2
february = pickup_month[february_bool]
february_rides = february.shape[0]

print(february_rides)

[1. 1. 1. 1.]
2013
[ True  True  True  True]
2013
[1. 1. 1. 1.]
800
176


Boolean Indexing with 2D ndarrays:

In [43]:
np.set_printoptions(suppress=True) 

## tip_amount = the 13th column
tip_amount = taxi[:,12]

## tip_bool = this column with TRUE/FALSE depending on whether the number is above 20
tip_bool = tip_amount > 20

## filtering the taxi array based on rows that are TRUE, and columns 6 to 15)
top_tips = taxi[tip_bool,5:14]
print(top_tips)
print(top_tips.shape)
np.set_printoptions(suppress=False)

[[   4.      2.     21.45 2004.     52.      0.8     0.     52.8   105.6 ]
 [   3.      3.      5.4    74.     80.      0.3     0.     24.05  104.35]
 [   4.      3.      8.55  832.     23.5     0.8     0.     25.     49.3 ]
 [   4.      2.     16.5  4340.     52.      0.8     5.54   21.     79.34]]
(4, 9)


Modifying values in an array:

In [46]:
taxi_modified = taxi.copy()
taxi_modified[1066,5] = 1
taxi_modified[:,0] = 16
taxi_modified[550:552,7] = taxi_modified[:,7].mean()

np.set_printoptions(suppress=True) 
print(taxi_modified.shape)
print(taxi_modified[548:554,5:9])
np.set_printoptions(suppress=False)

(2013, 15)
[[   2.            1.           12.18       2300.        ]
 [   2.            6.           15.8        1824.        ]
 [   3.            4.           12.92477894 1074.        ]
 [   3.            4.           12.92477894  974.        ]
 [   2.            4.           20.02       1979.        ]
 [   3.            6.            3.8         572.        ]]


Updating values using boolean arrays:

In [59]:
taxi_copy = taxi.copy()

## create a 1D array of values in the 14th column (index 13) of the taxi_copy array
total_amount = taxi_copy[:,8]

## modifying values in this array based on TRUE responses to a criteria
total_amount[total_amount < 60] = 0
print(trip_length)

[2037. 1520. 1462. ... 2822. 1083. 1711.]


In [64]:
np.set_printoptions(suppress=True) 
## bool = array[:, column_for_comparison] == value_for_comparison
## array[bool, column_for_assignment] = new_value

## create a new array based on the length of another
## name of array (zeros) = an array full of zeroes (np.zeros), with number of rows equal to the number of rows in taxi (taxi.shape[0]), and 1 column ([1])
zeros = np.zeros([taxi.shape[0],1])

## new array = combination (np.concatenate) of the 'taxi' array, and the 'zeros' array, along the column axis(1)
taxi_modified = np.concatenate([taxi,zeros],axis=1)
print(taxi_modified)

## longer method of assigning values:

## jfk_bool is a boolean array of all rows based on if the values in the 7th column are equal to 2
jfk_bool = taxi_modified[:, 6] == 2

## modifying values in the taxi_modified 16th column to 0 based on the boolean
## in the 'taxi_modified' array, 'rows equal to those with the True value' and 'column 16' = 1
taxi_modified[jfk_bool,15] = 1

## shorter methods:

## in the 'taxi_modified' array, the rows chosen are:
    ## a boolean array based on the 'taxi_modified' array where the value in the 6th column is 2 // taxi_modified[:, 5] == 2
## the column chosen is the one at index 15 (16th column)
## the new value is 1
taxi_modified[taxi_modified[:, 6] == 2, 15] = 1
taxi_modified[taxi_modified[:, 6] == 3, 15] = 1
taxi_modified[taxi_modified[:, 6] == 5, 15] = 1
print('\n')
print(taxi_modified[100:,5:])
np.set_printoptions(suppress=False) 

[[2016.      1.      1.   ...   69.99    1.      0.  ]
 [2016.      1.      1.   ...   54.3     1.      0.  ]
 [2016.      1.      1.   ...   37.8     2.      0.  ]
 ...
 [2016.      6.     30.   ...   63.34    1.      0.  ]
 [2016.      6.     30.   ...   44.75    1.      0.  ]
 [2016.      6.     30.   ...   54.84    2.      0.  ]]


[[ 3.    1.   17.7  ... 53.3   2.    0.  ]
 [ 4.    3.    8.6  ... 39.14  1.    1.  ]
 [ 4.    3.    8.64 ... 37.61  1.    1.  ]
 ...
 [ 2.    4.   17.48 ... 63.34  1.    0.  ]
 [ 2.    6.   12.76 ... 44.75  1.    0.  ]
 [ 2.    0.   17.54 ... 54.84  2.    0.  ]]


Determining which airport had the highest number of flights inbound:

In [65]:
## jfk is an array based on the taxi array, with all the columns, but where the 7th column in the taxi array is 2
jfk = taxi[taxi[:,6] == 2]

## jfk_count is a value equal to the shape of the jfk array, on the 0(row) axis
jfk_count = jfk.shape[0]
print(type(jfk_count))
print(jfk_count)

laguardia = taxi[taxi[:,6] == 3]
laguardia_count = laguardia.shape[0]
print(laguardia_count)

newark = taxi[taxi[:,6] == 5]
newark_count = newark.shape[0]
print(newark_count)

<class 'int'>
285
308
2


Calculating statistics for trips on clean data:

In [68]:
trip_mph = taxi[:,7] / (taxi[:,8] / 3600)

##cleaned_taxi is an array based on the taxi array, where the rows chosen are a boolean array based on whether trip_mph < 100,
cleaned_taxi = taxi[trip_mph<100]

## the mean_distance int is the mean of the values in the 8th column of the cleaned_taxi array
mean_distance = cleaned_taxi[:,7].mean()
print(round(mean_distance,2),"miles on average")

mean_length = cleaned_taxi[:,8].mean() / 60
print(round(mean_length,2),"minutes on average")

mean_total_amount = cleaned_taxi[:,13].mean()
print(round(mean_total_amount,2),"dollars on average")

12.9 miles on average
37.86 minutes on average
48.7 dollars on average


## Introduction to pandas

Importing pandas, reading csvs into dataframes, determining the type and shape of dataframes:

In [69]:
import pandas as pd
f500 = pd.read_csv('f500.csv',index_col=0)
f500.index.name = None

f500_type = type(f500)
print(f500_type)

f500_shape = f500.shape
print(f500_shape)

print(f500)

<class 'pandas.core.frame.DataFrame'>
(500, 16)
                                rank  revenues  revenue_change  profits  \
Walmart                            1    485873             0.8  13643.0   
State Grid                         2    315199            -4.4   9571.3   
Sinopec Group                      3    267518            -9.1   1257.9   
China National Petroleum           4    262573           -12.3   1867.5   
Toyota Motor                       5    254694             7.7  16899.3   
...                              ...       ...             ...      ...   
Teva Pharmaceutical Industries   496     21903            11.5    329.0   
New China Life Insurance         497     21796           -13.3    743.9   
Wm. Morrison Supermarkets        498     21741           -11.3    406.4   
TUI                              499     21655            -5.5   1151.7   
AutoNation                       500     21609             3.6    430.5   

                                assets  profit_chan

Printing head and tail of a dataframe:

In [70]:
f500_top_6 = f500.head(6)
print(f500_top_6)

f500_bottom_8 = f500.tail(8)
print(f500_bottom_8)

                          rank  revenues  revenue_change  profits  assets  \
Walmart                      1    485873             0.8  13643.0  198825   
State Grid                   2    315199            -4.4   9571.3  489838   
Sinopec Group                3    267518            -9.1   1257.9  310726   
China National Petroleum     4    262573           -12.3   1867.5  585619   
Toyota Motor                 5    254694             7.7  16899.3  437575   
Volkswagen                   6    240264             1.5   5937.3  432116   

                          profit_change                  ceo  \
Walmart                            -7.2  C. Douglas McMillon   
State Grid                         -6.2              Kou Wei   
Sinopec Group                     -65.0            Wang Yupu   
China National Petroleum          -73.7        Zhang Jianhua   
Toyota Motor                      -12.3          Akio Toyoda   
Volkswagen                          NaN      Matthias Muller   

           

Inspecting the information and data types in the dataframe:

In [71]:
f500.info()

<class 'pandas.core.frame.DataFrame'>
Index: 500 entries, Walmart to AutoNation
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   rank                      500 non-null    int64  
 1   revenues                  500 non-null    int64  
 2   revenue_change            498 non-null    float64
 3   profits                   499 non-null    float64
 4   assets                    500 non-null    int64  
 5   profit_change             436 non-null    float64
 6   ceo                       500 non-null    object 
 7   industry                  500 non-null    object 
 8   sector                    500 non-null    object 
 9   previous_rank             500 non-null    int64  
 10  country                   500 non-null    object 
 11  hq_location               500 non-null    object 
 12  website                   500 non-null    object 
 13  years_on_global_500_list  500 non-null    int64  
 14  em

Creating a series by selecting a specific column by name from a dataframe:

In [72]:
industries=f500["industry"]
industries_type=type(industries)
print(industries)
print(industries_type)

Walmart                                     General Merchandisers
State Grid                                              Utilities
Sinopec Group                                  Petroleum Refining
China National Petroleum                       Petroleum Refining
Toyota Motor                             Motor Vehicles and Parts
                                               ...               
Teva Pharmaceutical Industries                    Pharmaceuticals
New China Life Insurance          Insurance: Life, Health (stock)
Wm. Morrison Supermarkets                    Food and Drug Stores
TUI                                               Travel Services
AutoNation                                    Specialty Retailers
Name: industry, Length: 500, dtype: object
<class 'pandas.core.series.Series'>


Selecting columns from a dataframe by label:

In [73]:
## A single series only needs [""]
countries = f500["country"]

## Multiple columns requires [["",""]]
revenues_years = f500[["revenues","years_on_global_500_list"]]

## A slice of columns requires .loc[:,"":""]
ceo_to_sector = f500.loc[:,"ceo":"sector"]

print(type(countries))
print(type(revenues_years))
print(type(ceo_to_sector))
print(countries.head())
print(revenues_years.head())
print(ceo_to_sector.head())

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
Walmart                       USA
State Grid                  China
Sinopec Group               China
China National Petroleum    China
Toyota Motor                Japan
Name: country, dtype: object
                          revenues  years_on_global_500_list
Walmart                     485873                        23
State Grid                  315199                        17
Sinopec Group               267518                        19
China National Petroleum    262573                        17
Toyota Motor                254694                        23
                                          ceo                  industry  \
Walmart                   C. Douglas McMillon     General Merchandisers   
State Grid                            Kou Wei                 Utilities   
Sinopec Group                       Wang Yupu        Petroleum Refining   
China National Petroleu

Selecting rows from a dataFrame by label:

In [74]:
## Syntax to select rows and columns from a dataframe:
## df.loc[row_label, column_label]

## selecting a single row
toyota = f500.loc["Toyota Motor"]
print(type(toyota))
print(toyota)

## select a list of rows
drink_companies = f500.loc[["Anheuser-Busch InBev", "Coca-Cola", "Heineken Holding"]]
print(type(drink_companies))
print(drink_companies)

## select a slice object with labels
middle_companies = f500.loc["Tata Motors":"Nationwide",:]
print(type(middle_companies))
print(middle_companies)

<class 'pandas.core.series.Series'>
rank                                                   5
revenues                                          254694
revenue_change                                       7.7
profits                                          16899.3
assets                                            437575
profit_change                                      -12.3
ceo                                          Akio Toyoda
industry                        Motor Vehicles and Parts
sector                            Motor Vehicles & Parts
previous_rank                                          8
country                                            Japan
hq_location                                Toyota, Japan
website                     http://www.toyota-global.com
years_on_global_500_list                              23
employees                                         364445
total_stockholder_equity                          157210
Name: Toyota Motor, dtype: object
<class 'pandas.cor

Using value counts:

In [75]:
countries = f500["country"]
country_counts = countries.value_counts()
print(country_counts)
print(type(country_counts))

hq_locations = f500["hq_location"]
hql_counts = hq_locations.value_counts()
print(hql_counts)
print(type(hql_counts))

country
USA             132
China           109
Japan            51
Germany          29
France           29
Britain          24
South Korea      15
Netherlands      14
Switzerland      14
Canada           11
Spain             9
Australia         7
Brazil            7
India             7
Italy             7
Taiwan            6
Russia            4
Ireland           4
Singapore         3
Sweden            3
Mexico            2
Malaysia          1
Thailand          1
Belgium           1
Norway            1
Luxembourg        1
Indonesia         1
Denmark           1
Saudi Arabia      1
Finland           1
Venezuela         1
Turkey            1
U.A.E             1
Israel            1
Name: count, dtype: int64
<class 'pandas.core.series.Series'>
hq_location
Beijing, China         56
Tokyo, Japan           36
Paris, France          17
New York, NY           15
London, Britain        14
                       ..
Bangkok, Thailand       1
Midland, MI             1
Perth, Australia        1
Leuv

Selecting items from a series by label:

In [76]:
countries = f500['country']
countries_counts = countries.value_counts()

india = countries_counts["India"]
north_america = countries_counts[["USA","Canada","Mexico"]]
japan_to_spain = countries_counts["Japan":"Spain"]

print(india)
print(type(india))
print('\n')
print(north_america)
print(type(north_america))
print('\n')
print(japan_to_spain)
print(type(japan_to_spain))

7
<class 'numpy.int64'>


country
USA       132
Canada     11
Mexico      2
Name: count, dtype: int64
<class 'pandas.core.series.Series'>


country
Japan          51
Germany        29
France         29
Britain        24
South Korea    15
Netherlands    14
Switzerland    14
Canada         11
Spain           9
Name: count, dtype: int64
<class 'pandas.core.series.Series'>


Practising:

In [77]:
big_movers = f500.loc[["Aviva","HP","JD.com","BHP Billiton"],["rank","previous_rank"]]
print(big_movers.head())
bottom_companies = f500.loc["National Grid":"AutoNation",["rank","sector","country"]]
print(bottom_companies.head())
revenue_giants = f500.loc[["Apple","Industrial & Commercial Bank of China","China Construction Bank","Agricultural Bank of China"],"revenues":"profit_change"]
print(revenue_giants.head())

              rank  previous_rank
Aviva           90            279
HP             194             48
JD.com         261            366
BHP Billiton   350            168
                                       rank              sector  country
National Grid                           491              Energy  Britain
Dollar General                          492           Retailing      USA
Telecom Italia                          493  Telecommunications    Italy
Xiamen ITG Holding Group                494         Wholesalers    China
Xinjiang Guanghui Industry Investment   495         Wholesalers    China
                                       revenues  revenue_change  profits  \
Apple                                    215639            -7.7  45687.0   
Industrial & Commercial Bank of China    147675           -11.7  41883.9   
China Construction Bank                  135093            -8.7  34840.9   
Agricultural Bank of China               117275           -12.1  27687.8   

           

## Exploring Data with Pandas: Fundamentals

Looking at the head and information on the f500 dataset:

In [78]:
f500_head = f500.head(10)
f500_head.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, Walmart to Exxon Mobil
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   rank                      10 non-null     int64  
 1   revenues                  10 non-null     int64  
 2   revenue_change            10 non-null     float64
 3   profits                   10 non-null     float64
 4   assets                    10 non-null     int64  
 5   profit_change             8 non-null      float64
 6   ceo                       10 non-null     object 
 7   industry                  10 non-null     object 
 8   sector                    10 non-null     object 
 9   previous_rank             10 non-null     int64  
 10  country                   10 non-null     object 
 11  hq_location               10 non-null     object 
 12  website                   10 non-null     object 
 13  years_on_global_500_list  10 non-null     int64  
 14  em

Vectorized operation:

In [81]:
rank_change = f500["previous_rank"] - f500["rank"]
print(rank_change)

Walmart                             0
State Grid                          0
Sinopec Group                       1
China National Petroleum           -1
Toyota Motor                        3
                                 ... 
Teva Pharmaceutical Industries   -496
New China Life Insurance          -70
Wm. Morrison Supermarkets         -61
TUI                               -32
AutoNation                       -500
Length: 500, dtype: int64


Series data exploration methods:
- Series.max()
- Series.min()
- Series.mean()
- Series.median()
- Series.mode()
- Series.sum()

In [80]:
rank_change =  f500["previous_rank"] - f500["rank"]
rank_change_max = rank_change.max()
rank_change_min = rank_change.min()

print(rank_change_max)
print(rank_change_min)

226
-500


Series describe method:

In [82]:
rank = f500["rank"]
rank_desc = rank.describe()
prev_rank = f500["previous_rank"]
prev_rank_desc = prev_rank.describe()
print(rank_desc)
print(prev_rank_desc)

count    500.000000
mean     250.500000
std      144.481833
min        1.000000
25%      125.750000
50%      250.500000
75%      375.250000
max      500.000000
Name: rank, dtype: float64
count    500.000000
mean     222.134000
std      146.941961
min        0.000000
25%       92.750000
50%      219.500000
75%      347.250000
max      500.000000
Name: previous_rank, dtype: float64


Method chaining:

In [83]:
## Long method
'''
prev_rank = f500["previous_rank"]
print(prev_rank)
print('\n')
prev_rank_counts = prev_rank.value_counts()
print(prev_rank_counts)
print('\n')
zero_previous_rank = prev_rank_counts.loc[0]
print(zero_previous_rank)
'''

## Chained method
'''
zero_previous_rank = f500["previous_rank"].value_counts().loc[0]
print(zero_previous_rank)
'''

## OR JUST
print(f500["previous_rank"].value_counts().loc[0])

33


Dataframe exploration methods:
Determining the max value in each numeric column:

In [84]:
max_f500 = f500.max(numeric_only=True)
print(max_f500)

rank                            500.0
revenues                     485873.0
revenue_change                  442.3
profits                       45687.0
assets                      3473238.0
profit_change                  8909.5
previous_rank                   500.0
years_on_global_500_list         23.0
employees                   2300000.0
total_stockholder_equity     301893.0
dtype: float64


Dataframe describe method:

In [85]:
f500_desc=f500.describe()
print(f500_desc)

             rank       revenues  revenue_change       profits        assets  \
count  500.000000     500.000000      498.000000    499.000000  5.000000e+02   
mean   250.500000   55416.358000        4.538353   3055.203206  2.436323e+05   
std    144.481833   45725.478963       28.549067   5171.981071  4.851937e+05   
min      1.000000   21609.000000      -67.300000 -13038.000000  3.717000e+03   
25%    125.750000   29003.000000       -5.900000    556.950000  3.658850e+04   
50%    250.500000   40236.000000        0.550000   1761.600000  7.326150e+04   
75%    375.250000   63926.750000        6.975000   3954.000000  1.805640e+05   
max    500.000000  485873.000000      442.300000  45687.000000  3.473238e+06   

       profit_change  previous_rank  years_on_global_500_list     employees  \
count     436.000000     500.000000                500.000000  5.000000e+02   
mean       24.152752     222.134000                 15.036000  1.339983e+05   
std       437.509566     146.941961       

Assignment with pandas:

In [86]:
print(f500.loc["Dow Chemical","ceo"])
f500.loc["Dow Chemical","ceo"] = "Jim Fitterling"
print(f500.loc["Dow Chemical","ceo"])

Andrew N. Liveris
Jim Fitterling


Using Boolean Indexing with pandas Objects:

In [ ]:
## Creating a boolean series dependent on the industry column:
motor_bool = f500["industry"] == "Motor Vehicles and Parts"

## Creating a new series from the f500 dataframe of countries, dependent on True values in the boolean series:
motor_countries = f500.loc[motor_bool,"country"]
print(type(motor_countries))
print(motor_countries)

Using boolean arrays to assign values:
Changing values of 0 in the previous_rank column to NaN:

In [87]:
import numpy as np
prev_rank_before = f500["previous_rank"].value_counts(dropna=False).head()

## Creating a boolean series
zero_bool = f500["previous_rank"] == 0

## Assigning a na value to the previous_rank column where the zero_bool value is True
f500.loc[zero_bool,"previous_rank"] = np.nan

## Shorter method:
'''
f500.loc[[zero_bool = f500["previous_rank"] == 0],"previous_rank"] = np.nan
'''

## print the head of a series that shows the counts of each value in the previous_rank column, including na values
prev_rank_after = f500["previous_rank"].value_counts(dropna=False).head()
print(prev_rank_after)

previous_rank
NaN      33
1.0       1
302.0     1
334.0     1
325.0     1
Name: count, dtype: int64


Creating new columns:

In [88]:
## Creating a new column named "rank_change" that is the difference between two others:
f500["rank_change"] = f500["previous_rank"] - f500["rank"]
rank_change_desc = f500["rank_change"].describe()
print(rank_change_desc)
print(f500["rank_change"].head(5))

count    467.000000
mean      -3.533191
std       44.293603
min     -199.000000
25%      -21.000000
50%       -2.000000
75%       10.000000
max      226.000000
Name: rank_change, dtype: float64
Walmart                     0.0
State Grid                  0.0
Sinopec Group               1.0
China National Petroleum   -1.0
Toyota Motor                3.0
Name: rank_change, dtype: float64


Determining the two most common industries in the USA in the top 500, and,
the three most common sectors in China in the top 500:

In [89]:
industry_usa = f500.loc[f500["country"] == "USA", "industry"].value_counts().head(2)
print(industry_usa)
print('\n')
sector_china = f500.loc[f500["country"]=="China","sector"].value_counts().head(3)
print(sector_china)

industry
Banks: Commercial and Savings               8
Insurance: Property and Casualty (Stock)    7
Name: count, dtype: int64


sector
Financials     25
Energy         22
Wholesalers     9
Name: count, dtype: int64


## Exploring Data with Pandas: Intermediate

Creating a filtered dataframe to preview:

In [90]:
import pandas as pd
# read the data set into a pandas dataframe
f500 = pd.read_csv("f500.csv", index_col=0)
f500.index.name = None

# replace 0 values in the "previous_rank" column with NaN
f500.loc[f500["previous_rank"] == 0, "previous_rank"] = np.nan

# Select the rank, revenues, and revenue_change columns in f500, then show the first five rows
f500_selection = f500[["rank","revenues","revenue_change"]].head(5)
print(f500_selection)

                          rank  revenues  revenue_change
Walmart                      1    485873             0.8
State Grid                   2    315199            -4.4
Sinopec Group                3    267518            -9.1
China National Petroleum     4    262573           -12.3
Toyota Motor                 5    254694             7.7


Reading CSV files with pandas:
Not using index_col=0 or f500.index.name = None

In [91]:
f500 = pd.read_csv('f500.csv')
f500.loc[f500["previous_rank"] == 0, "previous_rank"] = np.nan
print(f500.head(2))

      company  rank  revenues  revenue_change  profits  assets  profit_change  \
0     Walmart     1    485873             0.8  13643.0  198825           -7.2   
1  State Grid     2    315199            -4.4   9571.3  489838           -6.2   

                   ceo               industry     sector  previous_rank  \
0  C. Douglas McMillon  General Merchandisers  Retailing            1.0   
1              Kou Wei              Utilities     Energy            2.0   

  country      hq_location                 website  years_on_global_500_list  \
0     USA  Bentonville, AR  http://www.walmart.com                        23   
1   China   Beijing, China  http://www.sgcc.com.cn                        17   

   employees  total_stockholder_equity  
0    2300000                     77798  
1     926067                    209456  


Using iloc to select by integer position:

In [92]:
## Pseudocode for iloc: df.iloc[row_index, column_index]

fifth_row = f500.iloc[4]
print(fifth_row)
print("\n")
company_value = f500.iloc[0,0]
print(company_value)

company                                     Toyota Motor
rank                                                   5
revenues                                          254694
revenue_change                                       7.7
profits                                          16899.3
assets                                            437575
profit_change                                      -12.3
ceo                                          Akio Toyoda
industry                        Motor Vehicles and Parts
sector                            Motor Vehicles & Parts
previous_rank                                        8.0
country                                            Japan
hq_location                                Toyota, Japan
website                     http://www.toyota-global.com
years_on_global_500_list                              23
employees                                         364445
total_stockholder_equity                          157210
Name: 4, dtype: object


Walmar

In [93]:
first_three_rows = f500.iloc[:3]
print(first_three_rows)
print("\n")

first_seventh_row_slice = f500.iloc[[0,6],:5]
print(first_seventh_row_slice)

         company  rank  revenues  revenue_change  profits  assets  \
0        Walmart     1    485873             0.8  13643.0  198825   
1     State Grid     2    315199            -4.4   9571.3  489838   
2  Sinopec Group     3    267518            -9.1   1257.9  310726   

   profit_change                  ceo               industry     sector  \
0           -7.2  C. Douglas McMillon  General Merchandisers  Retailing   
1           -6.2              Kou Wei              Utilities     Energy   
2          -65.0            Wang Yupu     Petroleum Refining     Energy   

   previous_rank country      hq_location                 website  \
0            1.0     USA  Bentonville, AR  http://www.walmart.com   
1            2.0   China   Beijing, China  http://www.sgcc.com.cn   
2            4.0   China   Beijing, China  http://www.sinopec.com   

   years_on_global_500_list  employees  total_stockholder_equity  
0                        23    2300000                     77798  
1          

Using .isnull() to create a boolean mask:

In [94]:
## new_df = df[column.isnull() to filter][column/s to show]

null_previous_rank = f500[f500["previous_rank"].isnull()][["company","rank","previous_rank"]]
print(null_previous_rank.head())

                    company  rank  previous_rank
48    Legal & General Group    49            NaN
90                   Uniper    91            NaN
123       Dell Technologies   124            NaN
138  Anbang Insurance Group   139            NaN
140         Albertsons Cos.   141            NaN


Using .iloc to assign rows and columns into new dataframe:

In [95]:
null_previous_rank = f500[f500["previous_rank"].isnull()]
top5_null_prev_rank = null_previous_rank.iloc[:5,:3]
print(top5_null_prev_rank)

                    company  rank  revenues
48    Legal & General Group    49    105235
90                   Uniper    91     74407
123       Dell Technologies   124     64806
138  Anbang Insurance Group   139     60800
140         Albertsons Cos.   141     59678


Pandas index alignment:

In [96]:
## Create a boolean series based on if the "previous_rank" column in f500 is not NaN
previously_ranked_bool = f500["previous_rank"].notnull()

## Filtering the f500 dataframe based on above bool
previously_ranked = f500[previously_ranked_bool]

## Creating a new column called "rank_change"
rank_change = previously_ranked["previous_rank"] - previously_ranked["rank"]

## Joining this series to the f500 dataframe
f500["rank_change"] = rank_change

## Top 5 in adjusted dataframe
print(f500[:5].head())

                    company  rank  revenues  revenue_change  profits  assets  \
0                   Walmart     1    485873             0.8  13643.0  198825   
1                State Grid     2    315199            -4.4   9571.3  489838   
2             Sinopec Group     3    267518            -9.1   1257.9  310726   
3  China National Petroleum     4    262573           -12.3   1867.5  585619   
4              Toyota Motor     5    254694             7.7  16899.3  437575   

   profit_change                  ceo                  industry  \
0           -7.2  C. Douglas McMillon     General Merchandisers   
1           -6.2              Kou Wei                 Utilities   
2          -65.0            Wang Yupu        Petroleum Refining   
3          -73.7        Zhang Jianhua        Petroleum Refining   
4          -12.3          Akio Toyoda  Motor Vehicles and Parts   

                   sector  previous_rank country      hq_location  \
0               Retailing            1.0     US

Using boolean operators:

In [97]:
## first boolean series
large_revenue = f500["revenues"] > 100000

## second boolean series
negative_profits = f500["profits"] < 0

## combined boolean series
combined = large_revenue & negative_profits

## using boolean series as mask to filter f500 into new df
big_rev_neg_profit = f500[combined]

print(big_rev_neg_profit)

                company  rank  revenues  revenue_change  profits   assets  \
32  Japan Post Holdings    33    122990             3.6   -267.4  2631385   
44              Chevron    45    107567           -18.0   -497.0   260078   

    profit_change               ceo                         industry  \
32         -107.5  Masatsugu Nagato  Insurance: Life, Health (stock)   
44         -110.8    John S. Watson               Petroleum Refining   

        sector  previous_rank country    hq_location                  website  \
32  Financials           37.0   Japan   Tokyo, Japan  http://www.japanpost.jp   
44      Energy           31.0     USA  San Ramon, CA   http://www.chevron.com   

    years_on_global_500_list  employees  total_stockholder_equity  rank_change  
32                        21     248384                     91532          4.0  
44                        23      55200                    145556        -14.0  


In [98]:
## Creating boolean series based on two criteria
filter_brazil_venezuela = (f500["country"] == "Brazil") | (f500["country"] == "Venezuela")

## Using boolean series as mask to filter df
brazil_venezuela=f500[filter_brazil_venezuela]

print(brazil_venezuela.head(5))

## Creating boolean series based on two criteria
filter_tech_outside_USA = ~(f500["country"] == "USA") & (f500["sector"] == "Technology")

## Using boolean series as mask to filter df
tech_outside_usa = f500[filter_tech_outside_USA].head(5)

print(tech_outside_usa.head())

                   company  rank  revenues  revenue_change  profits  assets  \
74               Petrobras    75     81405           -16.3  -4838.0  246983   
112  Itau Unibanco Holding   113     66876            21.4   6666.4  415972   
150        Banco do Brasil   151     58093           -13.4   2013.8  426416   
153         Banco Bradesco   154     57443            31.3   5127.9  366418   
190                    JBS   191     48825            -0.1    107.7   31605   

     profit_change                        ceo                       industry  \
74             NaN       Pedro Pullen Parente             Petroleum Refining   
112          -13.7    Candido Botelho Bracher  Banks: Commercial and Savings   
150          -52.3   Paulo Rogerio Caffarelli  Banks: Commercial and Savings   
153           -5.7  Luiz Carlos Trabuco Cappi  Banks: Commercial and Savings   
190          -92.3    Wesley Mendonca Batista                Food Production   

                        sector  previous_ran

Sorting values:

In [99]:
## filtered df based on boolean series where country = Japan
selected_rows = f500[f500["country"] == "Japan"]

## the above selected_rows, sorted from biggest to smallest, then selecting the first row, and finding the company name
top_japanese_employer = selected_rows.sort_values("employees",ascending=False).iloc[0]["company"]

print(top_japanese_employer)

Toyota Motor


Using Loops with pandas:

In [100]:
## Creating an empty dictionary to add values to later
top_employer_by_country = {}

## Creating a list of unique values in the "country" column
country = f500["country"].unique()
print("Unique countries:")
print(country)
print('\n')

## for each country in the country list:
for c in country:
    df = f500[f500["country"] == c]
    company = df.sort_values("employees",ascending=False).iloc[0]["company"]
    top_employer_by_country[c] = company
print(top_employer_by_country)

Unique countries:
['USA' 'China' 'Japan' 'Germany' 'Netherlands' 'Britain' 'South Korea'
 'Switzerland' 'France' 'Taiwan' 'Singapore' 'Italy' 'Russia' 'Spain'
 'Brazil' 'Mexico' 'Luxembourg' 'India' 'Malaysia' 'Thailand' 'Australia'
 'Belgium' 'Norway' 'Canada' 'Ireland' 'Indonesia' 'Denmark'
 'Saudi Arabia' 'Sweden' 'Finland' 'Venezuela' 'Turkey' 'U.A.E' 'Israel']


{'USA': 'Walmart', 'China': 'China National Petroleum', 'Japan': 'Toyota Motor', 'Germany': 'Volkswagen', 'Netherlands': 'EXOR Group', 'Britain': 'Compass Group', 'South Korea': 'Samsung Electronics', 'Switzerland': 'Nestle', 'France': 'Sodexo', 'Taiwan': 'Hon Hai Precision Industry', 'Singapore': 'Flex', 'Italy': 'Poste Italiane', 'Russia': 'Gazprom', 'Spain': 'Banco Santander', 'Brazil': 'JBS', 'Mexico': 'America Movil', 'Luxembourg': 'ArcelorMittal', 'India': 'State Bank of India', 'Malaysia': 'Petronas', 'Thailand': 'PTT', 'Australia': 'Wesfarmers', 'Belgium': 'Anheuser-Busch InBev', 'Norway': 'Statoil', 'Canada': 'Geo

Calculating top performing company per sector based on return on assets:

In [102]:
## creating a return on assets column
f500["roa"] = f500["profits"] / f500["assets"]

## creating a new dictionary
top_roa_by_sector = {}

## creating a list of unique sectors
sectors = f500["sector"].unique()
print("Unique sectors:")
print(sectors)
print('\n')

## For each value in sectors (i.e. each individual sector
for s in sectors:
    ## create a dataframe that is the f500 dataframe filtered down to only companies in that sector
    df = f500[f500["sector"] == s]
    ## a variable called "company" is the new dataframe sorted in descending order by "roa", then choose the first row, and only the company name
    company = df.sort_values("roa",ascending=False).iloc[0]["company"]
    # add a value to the dictionary, where the index is the sector, and the value is the company
    top_roa_by_sector[s] = company

print(top_roa_by_sector)

Unique sectors:
['Retailing' 'Energy' 'Motor Vehicles & Parts' 'Financials' 'Technology'
 'Wholesalers' 'Health Care' 'Telecommunications'
 'Engineering & Construction' 'Industrials' 'Food & Drug Stores'
 'Aerospace & Defense' 'Food, Beverages & Tobacco' 'Household Products'
 'Transportation' 'Materials' 'Chemicals' 'Media' 'Apparel'
 'Hotels, Restaurants & Leisure' 'Business Services']


{'Retailing': 'H & M Hennes & Mauritz', 'Energy': 'National Grid', 'Motor Vehicles & Parts': 'Subaru', 'Financials': 'Berkshire Hathaway', 'Technology': 'Accenture', 'Wholesalers': 'McKesson', 'Health Care': 'Gilead Sciences', 'Telecommunications': 'KDDI', 'Engineering & Construction': 'Pacific Construction Group', 'Industrials': '3M', 'Food & Drug Stores': 'Publix Super Markets', 'Aerospace & Defense': 'Lockheed Martin', 'Food, Beverages & Tobacco': 'Philip Morris International', 'Household Products': 'Unilever', 'Transportation': 'Delta Air Lines', 'Materials': 'CRH', 'Chemicals': 'LyondellBasell In

## Data Cleaning Basics

Importing a csv using encoding:

In [104]:
import pandas as pd
laptops = pd.read_csv("laptops.csv", encoding="Latin-1")
laptops.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   Manufacturer              1303 non-null   object
 1   Model Name                1303 non-null   object
 2   Category                  1303 non-null   object
 3   Screen Size               1303 non-null   object
 4   Screen                    1303 non-null   object
 5   CPU                       1303 non-null   object
 6   RAM                       1303 non-null   object
 7    Storage                  1303 non-null   object
 8   GPU                       1303 non-null   object
 9   Operating System          1303 non-null   object
 10  Operating System Version  1133 non-null   object
 11  Weight                    1303 non-null   object
 12  Price (Euros)             1303 non-null   object
dtypes: object(13)
memory usage: 132.5+ KB


Cleaning whitespace from column names:

In [105]:
print(laptops.columns)

new_columns = []

for c in laptops.columns:
    new_c = c.strip()
    new_columns.append(new_c)
    
print("\n")
print(new_columns)  

laptops.columns = new_columns
print("\n")
print(laptops.columns)

Index(['Manufacturer', 'Model Name', 'Category', 'Screen Size', 'Screen',
       'CPU', 'RAM', ' Storage', 'GPU', 'Operating System',
       'Operating System Version', 'Weight', 'Price (Euros)'],
      dtype='object')


['Manufacturer', 'Model Name', 'Category', 'Screen Size', 'Screen', 'CPU', 'RAM', 'Storage', 'GPU', 'Operating System', 'Operating System Version', 'Weight', 'Price (Euros)']


Index(['Manufacturer', 'Model Name', 'Category', 'Screen Size', 'Screen',
       'CPU', 'RAM', 'Storage', 'GPU', 'Operating System',
       'Operating System Version', 'Weight', 'Price (Euros)'],
      dtype='object')


In [107]:
## define a function that cleans column names
def columncleaner(col):
    ## strips whitespace
    col = col.strip()
    ## replaces Operting System with os
    col = col.replace("Operating System","os")
    ## replaces whitespace with underscores
    col = col.replace(" ","_")
    ## remove parentheses
    col = col.replace("(","")
    col = col.replace(")","")
    ## makes the string lowercase
    col = col.lower()
    ## returns the modified string
    return col

cleaned_column_list = []

## for each column name in the columns
for c in laptops.columns:
    ## apply the function to each column and return it as a new variable
    cleaned_column = columncleaner(c)
    ## assign this variable to the new columns list
    cleaned_column_list.append(cleaned_column)
    
## update the laptops.columns with the new columns list values
laptops.columns = cleaned_column_list
print(laptops.columns)

Index(['manufacturer', 'model_name', 'category', 'screen_size', 'screen',
       'cpu', 'ram', 'storage', 'gpu', 'os', 'os_version', 'weight',
       'price_euros'],
      dtype='object')


Exploring data types in the headers:

In [108]:
print(laptops["screen_size"].dtype)
print(laptops["screen_size"].unique())

unique_ram = laptops["ram"].unique()
print(unique_ram)

object
['13.3"' '15.6"' '15.4"' '14.0"' '12.0"' '11.6"' '17.3"' '10.1"' '13.5"'
 '12.5"' '13.0"' '18.4"' '13.9"' '12.3"' '17.0"' '15.0"' '14.1"' '11.3"']
['8GB' '16GB' '4GB' '2GB' '12GB' '6GB' '32GB' '24GB' '64GB']


Removing non-digit characters:

In [109]:
laptops["ram"] = laptops["ram"].str.replace('GB','')
unique_ram = laptops["ram"].unique()
print(unique_ram)

['8' '16' '4' '2' '12' '6' '32' '24' '64']


Converting columns to numeric dtypes:

In [110]:
laptops["ram"] = laptops["ram"].astype(int)
dtypes = laptops.dtypes
print(dtypes)

manufacturer    object
model_name      object
category        object
screen_size     object
screen          object
cpu             object
ram              int32
storage         object
gpu             object
os              object
os_version      object
weight          object
price_euros     object
dtype: object


Renaming columns:

In [112]:
laptops.rename({"ram":"ram_gb"},axis=1,inplace=True)
ram_gb_desc = laptops["ram_gb"].describe()
print(ram_gb_desc)

count    1303.000000
mean        8.382195
std         5.084665
min         2.000000
25%         4.000000
50%         8.000000
75%         8.000000
max        64.000000
Name: ram_gb, dtype: float64


Extracting values from strings:

In [115]:
laptops["gpu_manufacturer"] = (laptops["gpu"]
                                       .str.split()
                                       .str[0]
                              )
gpu_manufacturer_counts = laptops["gpu_manufacturer"].value_counts()
print(gpu_manufacturer_counts)

laptops["cpu_manufacturer"] = (laptops["cpu"]
                               .str.split()
                               .str[0]
                              )
cpu_manufacturer_counts = laptops["cpu_manufacturer"].value_counts()
print(cpu_manufacturer_counts)

gpu_manufacturer
Intel     722
Nvidia    400
AMD       180
ARM         1
Name: count, dtype: int64
cpu_manufacturer
Intel      1240
AMD          62
Samsung       1
Name: count, dtype: int64


Correcting bad values using mapping:

In [116]:
print(laptops["os"].value_counts())

mapping_dict = {
    'Android': 'Android',
    'Chrome OS': 'Chrome OS',
    'Linux': 'Linux',
    'Mac OS': 'macOS',
    'No OS': 'No OS',
    'Windows': 'Windows',
    'macOS': 'macOS'
}

laptops["os"] = laptops["os"].map(mapping_dict)
print(laptops["os"].value_counts())

os
Windows      1125
No OS          66
Linux          62
Chrome OS      27
macOS          13
Mac OS          8
Android         2
Name: count, dtype: int64
os
Windows      1125
No OS          66
Linux          62
Chrome OS      27
macOS          21
Android         2
Name: count, dtype: int64


Dropping missing values:

In [130]:
print('Columns with null values in rows:')
print(laptops.isnull().sum())
print('\n')

## removing rows with null values
laptops_no_null_rows = laptops.dropna(axis=0)
print('Columns with null values in rows:')
print(laptops_no_null_rows.isnull().sum(axis=0))
print('\n')

## removing cols with null values
print('Rows with null values in columns:')
print(laptops.isnull().sum(axis=1))
print('\n')
laptops_no_null_cols = laptops.dropna(axis=1)
print('Rows with null values in columns:')
print(laptops_no_null_cols.isnull().sum(axis=1))

Columns with null values in rows:
manufacturer          0
model_name            0
category              0
screen_size           0
screen                0
cpu                   0
ram_gb                0
storage               0
gpu                   0
os                    0
os_version          170
weight                0
price_euros           0
gpu_manufacturer      0
cpu_manufacturer      0
dtype: int64


Columns with null values in rows:
manufacturer        0
model_name          0
category            0
screen_size         0
screen              0
cpu                 0
ram_gb              0
storage             0
gpu                 0
os                  0
os_version          0
weight              0
price_euros         0
gpu_manufacturer    0
cpu_manufacturer    0
dtype: int64


Rows with null values in columns:
0       1
1       1
2       1
3       1
4       1
       ..
1298    0
1299    0
1300    0
1301    0
1302    0
Length: 1303, dtype: int64


Rows with null values in columns:
0    

Filling missing values:

In [132]:
value_counts_before = laptops.loc[laptops["os_version"].isnull(), "os"].value_counts()
laptops.loc[laptops["os"] == "macOS", "os_version"] = "X"

## in the laptops df, where the row for os is "No OS", the "os version" changes to:
laptops.loc[laptops["os"] == "No OS","os_version"] = "Version Unknown"

## where the laptops "os version" is null, get a value count from the "os" column
value_counts_after = laptops.loc[laptops["os_version"].isnull(), "os"].value_counts()

print(value_counts_before)
print('\n')
print(value_counts_after)

os
Linux        62
Chrome OS    27
Android       2
Name: count, dtype: int64


os
Linux        62
Chrome OS    27
Android       2
Name: count, dtype: int64


Challenge: clean a string column:
Converting weight to a float and renaming the column:

In [133]:
def columncleaner(col):
    col = col.replace("kgs","")
    col = col.replace("kg","")
    return col

## rename the column
laptops.rename({"weight":"weight_kg"},axis=1,inplace=True)

## remove letters
new_weights = []
for w in laptops["weight_kg"]:
    w = columncleaner(w)
    new_weights.append(w)
laptops["weight_kg"] = new_weights

## change dtype
laptops["weight_kg"] = laptops["weight_kg"].astype(float)

print(laptops["weight_kg"])

laptops.to_csv("laptops_cleaned.csv", index=False)

0       1.37
1       1.34
2       1.86
3       1.83
4       1.37
        ... 
1298    1.80
1299    1.30
1300    1.50
1301    2.19
1302    2.20
Name: weight_kg, Length: 1303, dtype: float64


## Guided Project: Exploring eBay Car Sales Data

Please see separate project notebook.